version: "3.7"

services:
    db_postgres: 
        image: postgres:10
        container_name: redis_demo_postgres
        environment:
            POSTGRES_PASSWORD: 'postgres'
            POSTGRES_USER: 'postgres'
            POSTGRES_DB: 'redis_demo'
        ports: 
        - 5435:5432