spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/redis_demo
    username: postgres
    password: postgres
  flyway:
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
